apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server.monitoring.svc.cluster.local

#metadata:
#  labels:
#    grafana_dashboard: "1"
#  name: grafana-dashboards-configmap
#  namespace: monitoring
#data:
#  my-dashboard.json: |-
 #   {
 #     "annotations": {
 #       "list": []
 #  }
